services:
  grpc-server:
    build:
      context: ..
      dockerfile: Dockerfile.grpc
    networks:
      - logengine.io-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logengine-grpc.rule=Host(`${GRPC_DOMAIN:-rpc.logengine.io}`)"
      - "traefik.http.routers.logengine-grpc.entrypoints=websecure"
      - "traefik.http.routers.logengine-grpc.tls.certResolver=letsencrypt"
      - "traefik.http.services.logengine-grpc.loadbalancer.server.port=30001"
      - "traefik.http.services.logengine-grpc.loadbalancer.server.scheme=h2c"

networks:
  logengine.io-network:
