services:
  http-server:
    build:
      context: ..
      dockerfile: Dockerfile.http
    environment:
      DB_URI: postgres://${POSTGRES_USER:-logengine}:${POSTGRES_PASSWORD:-logengine}@postgres:5432/${POSTGRES_DB:-logengine}?sslmode=disable
      RABBITMQ_URI: amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672/
      ADMIN_USERNAME: ${ADMIN_USERNAME:-logengine}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-logengine}
    networks:
      - dokploy-network
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logengine-http.rule=Host(`${HTTP_DOMAIN:-api.logengine.io}`)"
      - "traefik.http.routers.logengine-http.entrypoints=websecure"
      - "traefik.http.routers.logengine-http.tls.certResolver=letsencrypt"
      - "traefik.http.services.logengine-http.loadbalancer.server.port=8080"

networks:
  dokploy-network :
    external: true
