services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-logengine}
      POSTGRES_USER: ${POSTGRES_USER:-logengine}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-logengine_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-logengine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network :

volumes:
  postgres_data:
