# Dependabot configuration pour LogEngine
# Vérifie automatiquement les vulnérabilités et propose des mises à jour

version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"

  # NPM - Admin UI
  - package-ecosystem: "npm"
    directory: "/apps/ui/admin"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    commit-message:
      prefix: "deps(admin)"
      include: "scope"

  # NPM - Landing Page
  - package-ecosystem: "npm"
    directory: "/apps/ui/landing-page"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    commit-message:
      prefix: "deps(landing)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
